name: VW Beetles
favicon: null
layout_spectrum: 0.2452
typography_spectrum: 0.65159
title: VW Beetles
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050505'
    - '#82d0da'
    - '#515352'
    - '#8c8c8c'
    - '#ae1611'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
