name: VW Beetles
favicon: null
layout_spectrum: 0.37449
typography_spectrum: 0.73778364690952
title: VW Beetles
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e0f11'
    - '#d3dce5'
    - '#747c7f'
    - '#a6475b'
    - '#d77f9b'
  brandStrength: 0.7167818071320653
  lightness: 0.6894247778691351
  saturation: 0.17064221994951367
  rhythmicContrast: 0.791481378255412
purpose: []
