name: VW Beetles
favicon: null
layout_spectrum: 0.37449
typography_spectrum: 0.65159
title: VW Beetles
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e0f11'
    - '#d3dce5'
    - '#747c7f'
    - '#a6475b'
    - '#d77f9b'
  brandStrength: 0.375
  lightness: 0.75
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
